### ISSUE TITLE
上传成功的消息框中，隐藏空的 symmetricKeyMaterial

### ISSUE THREAD

**Issue by czyczk** [zyw271828/blockade#16]
上传成功的消息框中，若 API 给的 response 中不含 symmetricKeyMaterial

如
```
{"resourceId":"1493509399090565120","transactionId":"0x2fcf5f6f8b4a9df6f8c9e84964c3fcf45c1315618feb6a2386160fe94370d5a7"}
```

则最好隐藏空的 SymmetricKeyMaterial 行。

![image](https://user-images.githubusercontent.com/18629839/154027262-cb0a4852-7963-4d37-8952-0eb3ef8ba01c.png)

因为这种情况发生在资源类型为“明文”时，这时出现密钥相关的词汇容易造成困惑。

**Comment by zyw271828** [comment]
325198030dade7ffd2fc32e918575c7da1b499e5
已修复
