### ISSUE TITLE
优化确定的 ID 的查询逻辑与空结果显示

### ISSUE THREAD

**Issue by czyczk** [zyw271828/blockade#17]
**1. 确定的 ID 的查询逻辑**

对于确定的 ID 的查询，使用 `metadata` API 而非 `list`。因为后者实现涉及链码富查询，在当前 ink! 版本中未实现，且比起前者运行效率更低。

若 `metadata` 返回 200，则其内容正好可以作为该条目的 metadata 信息。
若返回 404，则显示空列表。

**2. 空列表展示方式**

适用于所有列表类，包括但不限于 query 结果展示、auth 结果展示等。
以任意方式在列表中展示出其内容为空的信息，从而和后端正在运行以及运行出错等情况显著地区分开来。
例如专用一行来显示“无数据”或“无条目”等。

![image](https://user-images.githubusercontent.com/18629839/154030201-5e0da7a7-d985-4848-adcd-d934741c9f74.png)

**Comment by zyw271828** [comment]
7178ab8b19acbef3b2f856db647b273aeaae5bd3
246408e935895a62c291845a9c0ee685718fb232
已修复
