### ISSUE TITLE
资源详情对话框缺少信息

### ISSUE THREAD

**Issue by czyczk** [zyw271828/blockade#8]
看 OneDrive 草稿的 Document - Query 页。

**Comment by zyw271828** [comment]
3857ee6803a6189915ee50d2f9303e421345426e 完成文档查询详情对话框的交互逻辑
ef28b3e84ecb21b6e7f4ed829562c35e88474da2 完成资产查询详情对话框的交互逻辑

**Comment by zyw271828** [comment]
d2d95a3e092c8c8512e5fb84b8d59ed66927e9a6
已修复
